name: DreamHost DDNS
version: "1.0.2"
slug: dreamhost_ddns
description: Update DreamHost DNS A record with current WAN IP
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7

options:
  api_key: ""
  dns_record: ""
  interval: 300

schema:
  api_key: str
  dns_record: str
  interval: int

map:
  - config:rw
