name: DreamHost DDNS
version: "1.0.20"
slug: dreamhost_ddns
image: "https://raw.githubusercontent.com/PRProd/home-assistant-addon-dreamhost-ddns/refs/heads/main/addon-dreamhost-ddns/dreamhost-icon.png"
description: Automatically update a DreamHost DNS A record with your public IP.
url: https://github.com/PRProd/home-assistant-addon-dreamhost-ddns
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7

options:
  dns_record: "ha.example.com"
  api_key: ""
  interval: 300

schema:
  dns_record: str
  api_key: password
  interval: int(30,86400)

map:
  - config:rw
